---
title: "Multivariate methods for heterogeneous data"
author:
- name: Lucas Schiffer
  affiliation: Section of Computational Biomedicine, Boston University
output:
  BiocStyle::html_document
vignette: |
  %\VignetteIndexEntry{Multivariate methods for heterogeneous data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Goals for this chapter

In this chapter, we will:

* Extend linear dimension reduction methods to cases when the distances between observations are available, known as multidimensional scaling (MDS) or principal coordinates analysis.

* Find modifications of MDS that are nonlinear and robust to outliers.

* Encode combinations of categorical data and continuous data as well as so-called ‘supplementary’ information. We will see that this enables us to remove batch effects.

* Use chi-square distances and correspondence analysis (CA) to see where categorical data (contingency tables) contain notable dependencies.

* Generalize clustering methods that can uncover latent variables that are not categorical. This will allow us to detect gradients, “pseudotime” and hidden nonlinear effects in our data.

* Generalize the notion of variance and covariance to the study of tables of data from multiple different data domains.

# A few extra resources

* <https://www.sequentix.de/gelquest/help/cluster_analysis.htm>
* <https://en.wikipedia.org/wiki/Principal_component_analysis>
* <https://en.wikipedia.org/wiki/Multidimensional_scaling>
* <https://en.wikipedia.org/wiki/Metric_(mathematics)>

# UMAP slides

* <https://tinyurl.com/y4578e9q>

# Dimensionality reduction slides

* <https://tinyurl.com/y3brzu2e>

# Exercises

To be done together...

# Session info

```{r}
sessionInfo()
```
